První upload
nvbach91/4IZ268-2024-2025-ZS pull request #172
Opened 2024-12-14 13:07 UTC by davidmalasek

Aplikace je nyní dostupná na: https://eso.vse.cz/~mald16/sp2/

2025-01-14 18:56 UTC, davidmalasek commented
Vážený pane inženýre,

v souvislosti se zvolenou API pro tuto práci se bohužel vyskytl problém. V mezičase její autor výrazně omezil počet requestů a to stěžuje plynulý chod aplikace.

Situaci jsem se snažil řešit vlastní instancí API. Nyní jsem schopný z API dostat textová data, ale obrázky (provedení cviků) již bohužel ne... Momentálně to vypadá tak, že jsou místo obrázku nekonečně točící se spinnery.

Budu velmi vděčný za jakoukoli radu nebo doporučení, jak tuto situaci nejlépe vyřešit. Děkuji.

2025-01-16 17:27 UTC, nvbach91 commented
- aplikaci musite mit jako single-page, tj. 1x html soubor, a obsah se meni pomoci javascriptu bez presmerovani, bez reloadu
- elementy z html nevybirat opakovane
- nepouzivat inline css
- nesmi se zasahovat do DOM v cyklu (pridavani novych elementu, zmena atributu, zmena obsahu elementu, ...)
- data (quotes) se nesmi psat do kodu
- remove exercise by melo byt s potvrzenim
- mohl byste pridat funkci aby uzivatel si mohl pridavat a spravovat rutiny, ktere se sklada z ruznych cviku?

2025-01-17 10:12 UTC, nvbach91 commented
- cache exercices data

2025-01-17 14:42 UTC, nvbach91 requested changes
z pull requestu vymazte prosim soubory ktere do projektu nepatri nebo jsou zbytecne navic

2025-01-18 10:32 UTC, nvbach91 approved these changes

2025-01-18 10:32 UTC, merged

2025-01-18 12:47 UTC, davidmalasek commented
Dobrý den @nvbach91,

včera po obhajobě jste mi sdělil, že mi vychází známka 2, avšak v INSIS mi dnes přišla známka 3.

Co mohu udělat pro to, abych dostal známku 2, případně 1?

Děkuji

2025-01-19 12:45 UTC, nvbach91 commented
Můžete např. se podívat na to jaké máte chyby v SP1. U SP2 se podívejte na to, jaké tam jsou nedostatky z pohledu kódu, přičemž vycházejte z věcí, které jsme si říkali na cvičeních a které jsou uvedeny v pokynech pro SP2

2025-01-21 08:22 UTC, davidmalasek commented
Chyby opraveny viz https://github.com/nvbach91/4IZ268-2024-2025-ZS/issues/262