vava06 - sp2
nvbach91/4IZ268-2024-2025-ZS pull request #183
Opened 2024-12-15 16:49 UTC by vava06

Odkaz na moji aplikaci: https://eso.vse.cz/~vava06/sp2/

2025-01-29 22:21 UTC, nvbach91 commented
nekorektní struktura souborů a složek v rámci Pull Requestu

2025-01-30 09:15 UTC, vava06 commented
Dobrý den, je to takto v pořádku? Děkuji, za zpětnou vazbu.

2025-01-30 18:02 UTC, nvbach91 requested changes
- pridat indikaci asynchronniho nacitani dat
- proc se tlacitko predchozi otazka zobrazuje az po zvoleni odpovedni v aktualni otazce?
- jiz zodpovezena otazka by mela zustat zodpovezenou po celou dobu testu, i pri vraceni se na predchozi na predchozi otazku...
- proc jsou promenne pojmenovany velkymi pismeny?
- funkce deklarovat jako lokalni pomoci `const`
- data z localStorage nenacitat opakovane ale nacist pouze jednou na zacatku programu a drzet je v in-memory objektu, jehoz obsah se pak bude menit a ukladat do localStorage
- elementy z HTML nevybirat opakovane v prubehu programu, ale vybirat pouze jednou a ukladat je do promennych
- API BASE_URL ukladat do konstanty
- dodrzet DRY princip (category-1-button, category-2-button, ...) - pouzivat cyklus
- vyber elementu z HTML provest pomoci jQuery, ne `document.getElementById`
- pridat moznost zvoleni urovne obtiznosti otazek

2025-01-31 13:37 UTC, nvbach91 approved these changes

2025-01-31 13:37 UTC, merged