sitz00-sp2
nvbach91/4IZ268-2024-2025-ZS pull request #186
Opened 2024-12-15 17:02 UTC by ZuzSi

Link to application: http://eso.vse.cz/~sitz00/sp2/

2025-01-09 16:55 UTC, nvbach91 commented
- nesmime do localStorage ukladat cely JSON ktery se vrati z API, ale jenom klicove informace ze kterych lze opetovne dostat ta stejna data. v tomhle pripade staci ukladat ta slova ktera jsou spravne napsana a pak kdyz se zvoli slovo z historie tak se znovu zavola na API.
- pridejte k tomu ukladani jeste datum a cas kdy doslo k vyhledani slova
- nesmime modifikovat DOM v cyklu, viz searchHistory items
- mazani historie by melo byt s potvrzenim
- pridejte moznost serazeni historie slov podle abecedy

2025-01-10 08:55 UTC, nvbach91 commented
jak probiha kontrola existujiciho slova
smazat jednoliva slova
dozobrazit chybejici informace
navigace mezi slovy antonyms a synonym
struktura json word: isodate

2025-01-10 14:56 UTC, nvbach91 approved these changes

2025-01-10 14:57 UTC, nvbach91 requested changes
nespravna struktura slozek

![image](https://github.com/user-attachments/assets/ea0da0e3-d094-432e-a5ff-8bcf37c1c53f)

nespravne soubory vymazte z pull requestu podle navodu na wiki

2025-01-10 15:43 UTC, ZuzSi commented
opraveno

2025-01-11 12:37 UTC, nvbach91 commented
neni opraveno

2025-01-11 14:26 UTC, ZuzSi commented
Omlouvám se, už se povedlo.

2025-01-11 21:59 UTC, nvbach91 approved these changes

2025-01-11 21:59 UTC, merged