mast06-sp2
nvbach91/4IZ268-2024-2025-ZS pull request #195
Opened 2024-12-15 20:09 UTC by mast06t

2025-01-30 00:54 UTC, mast06t commented
https://eso.vse.cz/~mast06/sp2/

2025-01-30 18:27 UTC, nvbach91 requested changes
- vyprazdnit jidelnicek vzdy s potvrzenim
- funkce deklarovat jako lokalni pomoci `const`
- nepouzivat inline javascript
- data z localStorage nenacitat opakovane ale nacist pouze jednou na zacatku programu a drzet je v in-memory objektu, jehoz obsah se pak bude menit a ukladat do localStorage
- osetrit hodnotu inputu
- nezasahovat do DOM v cyklu (pridavani novych elementu, zmena atributu, obsahu, atd.)
- elementy z HTML nevybirat opakovane v prubehu programu, ale vybirat pouze jednou a ukladat je do promennych
- nutricni hodnoty zaokrouhlovat na vhodny pocet desetinnych mist
- pridat moznost zobrazeni detailu produktu v modalovem okne, kde bude vice zakladnich informaci a priznaku

2025-01-31 11:48 UTC, nvbach91 commented
- potvrzeni pomoci SweetAlert
- zobrazit prehled kalorii poslednich 14 dni v modalovem okne

2025-01-31 21:45 UTC, mast06t commented
Nevím proč, ale když jsem nahrál práci přes FTP, nenahraje se skutečná verze. Prosím Vás tedy o spuštění na live serveru, tam to fungovalo bez problémů.

2025-02-01 09:46 UTC, nvbach91 requested changes
- tydenni vypis se nema zobrazovat jako nova samostatna stranka, ale jako modalove okno ve stejne strance aplikace
- elementy z HTML nevybirat opakovane v prubehu programu, ale vybirat pouze jednou a ukladat je do promennych
- nezasahovat do DOM v cyklu (pridavani novych elementu, zmena atributu, obsahu, atd.)

2025-02-04 14:21 UTC, nvbach91 commented
Odevzdejte ještě jednou, poslední commit je špatně

![image](https://github.com/user-attachments/assets/59b81dc5-3633-40d9-a597-33be5a32575b)

2025-02-05 12:49 UTC, nvbach91 commented
dejte to taky na server eso

2025-02-06 10:23 UTC, closed without merging