biza02-sp2
nvbach91/4IZ268-2024-2025-ZS pull request #198
Opened 2024-12-15 20:49 UTC by Anezbiz

link to application: https://eso.vse.cz/~biza02/sp2/

2025-01-23 21:38 UTC, nvbach91 requested changes
- nepouzivat inline javascript
- nektere texty nejsou vubec videt

![image](https://github.com/user-attachments/assets/2c147214-0d7a-4dae-a855-1a8fd8176dce)

![image](https://github.com/user-attachments/assets/f5c940c7-19de-4908-95bc-29fd6d7230f1)

- nesmi byt mozne zadat datumy od-do v opacnem poradi
- v pripade chyb zobrazovat vic informaci nez jen pouze `An unhandled error occurred. Please check the console` ...
- aplikace nesmi mazat korenovy path kontext v URL
- chybi indikace nacitani dat
- vyhledavani lokaci nefunguje

2025-01-30 18:28 UTC, nvbach91 commented
Dobry den, Budete neco odevzdavat?

2025-01-30 22:04 UTC, Anezbiz commented
Dobrý den,
ano budu, moc se omlouvám zapomněla jsem to vložit, hned to tam dám.
Bízková Anežka

čt 30. 1. 2025 v 19:28 odesílatel Nguyen Viet Bach ***@***.***>
napsal:

> Dobry den, Budete neco odevzdavat?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nvbach91/4IZ268-2024-2025-ZS/pull/198#issuecomment-2625263507>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BLOELJMLTLA6WUGYNJOMHRL2NJVMTAVCNFSM6AAAAABTU4GSKGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMRVGI3DGNJQG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-30 23:19 UTC, nvbach91 requested changes
- nepouzivat inline javascript
- elementy z HTML nevybirat opakovane v prubehu programu, ale vybirat pouze jednou a ukladat je do promennych
- odstranit kod ktery se nikde v projektu nepouziva
- ma funkce plan route zobrazovat leteckou drahu?
- weather forecast input a tlacitko maji byt v ramci elementu `<form>` s udalosti submit
- create new trip nefunguje

2025-01-31 13:45 UTC, closed without merging