vodd01-sp2
nvbach91/4IZ268-2024-2025-ZS pull request #200
Opened 2024-12-15 21:51 UTC by Dandicek

Link to my application: https://eso.vse.cz/~vodd01/sp2/

2025-01-30 16:31 UTC, nvbach91 requested changes
prace neni odevzdana

2025-01-30 20:23 UTC, Dandicek commented
Dobrý večer,
omlouvám se za pozdní odevzdání, soubory by měly být nahrané. Mohu před zítřejší obhajobou dále upravovat?

2025-01-31 13:52 UTC, nvbach91 approved these changes

2025-01-31 13:52 UTC, merged

2025-01-31 13:56 UTC, nvbach91 commented
Ještě musíte opravit SP1, máte tam málo bodů viz https://github.com/nvbach91/4IZ268-2024-2025-ZS/issues/3

2025-01-31 13:56 UTC, nvbach91 commented
@Dandicek

2025-01-31 15:19 UTC, Dandicek commented
> Ještě musíte opravit SP1, máte tam málo bodů viz #3

Dobrý den,

už jsem opravil i první semestrální práci.

2025-01-31 16:16 UTC, nvbach91 commented
Odevzdani opravy viz pokyny https://github.com/nvbach91/4IZ268-2024-2025-ZS/wiki/P-Pokyny-SP1

2025-01-31 16:32 UTC, Dandicek commented
> Odevzdani opravy viz pokyny https://github.com/nvbach91/4IZ268-2024-2025-ZS/wiki/P-Pokyny-SP1

Vytvořil jsem nový Issue pro opravu a popsal opravené chyby.