hree01-sp2 pilotní verze
nvbach91/4IZ268-2024-2025-ZS pull request #202
Opened 2024-12-15 22:55 UTC by hree01

Odevzdávám pilotní verzi sp2

2025-01-23 20:46 UTC, nvbach91 commented
Link to application: https://eso.vse.cz/~hree01/sp2/

2025-01-23 20:54 UTC, nvbach91 requested changes
- vyhledavaci formular s jejich prvky musi byt v elementu form a zachycenou udalosti submit
- chybi indikace nacitani dat pri vyberu hlavnich mest v levem panelu
- klikatelna tlacitka musi mit k tomu prizpusobeny kurzor
- v sekci favorite cities se nesmi duplikovat informace o pocasi

![image](https://github.com/user-attachments/assets/47444c0a-2e32-4f13-8152-c1f9a2dea265)

- elementy z HTML nevybirat opakovane v prubehu programu, ale ukladat do promennych
- nezasahovat do DOM v cyklu (pridavani novych elementu, zmena atributu, obsahu, ...)

2025-01-24 11:22 UTC, nvbach91 commented
- do oblibenych ukladat i stat pro rozliseni mest se stejnymi nazvy

2025-01-24 13:56 UTC, hree01 reviewed
Zapomněla jsem přidat upravenou verzi do složky www. Odevzdám znovu

2025-01-24 16:41 UTC, nvbach91 approved these changes

2025-01-24 16:41 UTC, merged