ruzj15-hw05
nvbach91/4IZ268-2024-2025-ZS pull request #38
Opened 2024-10-24 19:03 UTC by Jackoubek

2024-10-24 22:09 UTC, nvbach91 requested changes

2024-10-24 22:09 UTC, nvbach91 commented on www/ruzj15/hw05/homework.js
> +
a zbytek ukolu?

2024-10-25 08:29 UTC, Jackoubek commented on www/ruzj15/hw05/homework.js
> +
zvláštní úkol jsem udělal celý, zkusím nahrát znovu

2024-10-31 22:33 UTC, nvbach91 approved these changes

2024-10-31 22:33 UTC, merged