hoza01-hw06
nvbach91/4IZ268-2024-2025-ZS pull request #67
Opened 2024-10-29 15:26 UTC by anezka03

https://eso.vse.cz/~hoza01/hw06/
reviewer - @stolfova

2024-10-29 15:27 UTC, stolfova approved these changes
vše funguje:)

2024-10-31 23:19 UTC, nvbach91 commented
ale Pull Request neni vlaidni, takze prosim novy Pull Request do spravneho adresare

2024-10-31 23:20 UTC, nvbach91 reviewed
.

2024-10-31 23:21 UTC, nvbach91 requested changes
.

2024-11-01 15:12 UTC, closed without merging